### ISSUE TITLE
Chararcters problems with the theme

### ISSUE THREAD

**Issue by nanotime** [fishery/joker#1]
Well, it's simple and not a issue per-se but i need to know what i'm missing here, look at my theme:

![captura de pantalla de 2016-03-09 09-01-43](https://cloud.githubusercontent.com/assets/1323582/13636953/cbc0ef62-e5d6-11e5-8550-4d8d57e577ab.png)

A specific font is required here? D:

**Comment by bucaran** [comment]
Yes, you need a [powerline](https://github.com/powerline/fonts) font.

Check out also the [terminal settings](https://github.com/fishery/joker#terminal-settings) for other details.

**Comment by nanotime** [comment]
Hey, yeap just right now i notice that... sorry, noob problems. Close this sh*t xD

**Comment by bucaran** [comment]
:laughing: Alright.
