### ISSUE TITLE
master shows in the prompt and I want to undo it

### ISSUE THREAD

**Issue by lamiastella** [fishery/joker#3]
So I did a sloppy "git init" in my home directory and it keeps showing master before the prompt afterwards. How can I remove master now or how can I undo it? I just want to see it if a directory is really really really a git repo not something I just accidentally did a "git init" in.

 ~   master          ls

**Comment by bucaran** [comment]
@lamiastella  Done. 2af5141

Here is how it looks now.

<img width="1280" alt="screen shot 2016-03-10 at 8 10 49 pm" src="https://cloud.githubusercontent.com/assets/8317250/13667910/592c2670-e6fc-11e5-8df0-4e5816fbc881.png">

**Comment by bucaran** [comment]
Closing as resolved.

2af5141

**Comment by bucaran** [comment]
@lamiastella I just realized, that your problem was a different thing and not what I replied. My apologies for not properly reading your issue.

If you created a dummy git repo in your home directory, just delete `.git` directory.

```
if test -d ~/.git
    rm -rf ~/.git
end
```
