### ISSUE TITLE
Not correct working right prompt

### ISSUE THREAD

**Issue by alphatroya** [fishery/joker#4]
I install joker throughout fisher, but right prompt seems to be working wrong. Any ideas about what it been caused by? 

<img width="1280" alt="2016-03-11 15 05 45" src="https://cloud.githubusercontent.com/assets/4927633/13701874/d216ec42-e79b-11e5-8eed-68eab81d563c.png">

**Comment by bucaran** [comment]
This must be a problem with `date +%r`.

In your command line, enter:

```
date +%r
```

What is your output?

Also, what is your operating system?

**Comment by alphatroya** [comment]
nothing in output

<img width="1277" alt="2016-03-11 15 46 29" src="https://cloud.githubusercontent.com/assets/4927633/13702532/73fd114a-e7a0-11e5-8bfd-cd3396fc359c.png">

OS is OSX, terminal - iTerm

**Comment by bucaran** [comment]
I am on OS X too, El Capitan.

Do you happen to be using the GNU version of `date`? Should not be a problem, but I can't figure what's wrong with your `date` command.

When you type `date +%r`, the output should be:

<img width="359" alt="screen shot 2016-03-11 at 10 40 02 pm" src="https://cloud.githubusercontent.com/assets/8317250/13703539/35cefc0a-e7da-11e5-97b1-dab466c1088a.png">

Could this be an issue with locale settings?

**Comment by alphatroya** [comment]
Maybe problem in Russian locale, there is not problem in another prompts: 
<img width="1280" alt="2016-03-11 16 41 57" src="https://cloud.githubusercontent.com/assets/4927633/13703662/9a0b3120-e7a8-11e5-9ddf-eaebf59bb7dc.png">

There are any ways to change `date` locale?

**Comment by bucaran** [comment]
Bobthefish is using a different date format string that shows also the date and the weekday, so changing to that in the joker would work, but that's not what we want right?

How do get the current time from the command line, like in the example I posted above?

**Comment by bucaran** [comment]
Try this command:

```fish
date +"%T"
```

If that one works, I'll patch joker with that one.

**Comment by alphatroya** [comment]
Yes, this works 🎉
<img width="1280" alt="2016-03-11 16 52 55" src="https://cloud.githubusercontent.com/assets/4927633/13703846/c2d20a38-e7a9-11e5-9846-a46d2d12c81a.png">

**Comment by bucaran** [comment]
Alright, let me ask you one more favor, just to be sure:

What if you run the command with quotes?

```
date +"%r"
```

**Comment by alphatroya** [comment]
Nothing 
<img width="554" alt="2016-03-11 17 15 26" src="https://cloud.githubusercontent.com/assets/4927633/13704422/eb41d5c2-e7ac-11e5-835c-e448e46cd603.png">

**Comment by bucaran** [comment]
Alright, `fisher u joker` and see if everything works as it should.

**Comment by alphatroya** [comment]
Thanks
<img width="1280" alt="2016-03-11 17 21 59" src="https://cloud.githubusercontent.com/assets/4927633/13704603/cb26b1ee-e7ad-11e5-8d63-fa42660053ab.png">

**Comment by bucaran** [comment]
Lol, my notification is hiding the hour display, but guess it's working :laughing:
